clear all; clc;
addpath(genpath('.'));
filepath = 'cedric-jake-design.txt';

[Joints_Array,            ...
MemberConnectivity_Array, ...
ReactionJoints_Array,     ...
ReactionVector_Array,     ...
LoadJoints_Array,         ...
LoadVectors_Array] = ReadInput3D(filepath)

[barforces, reacforces] = ForceAnalysis3D(Joints_Array, ...
                                          MemberConnectivity_Array, ...
                                          ReactionJoints_Array, ...
                                          ReactionVector_Array, ...
                                          LoadJoints_Array, ...
                                          LoadVectors_Array);

plottruss(Joints_Array, ...
MemberConnectivity_Array, ...
barforces, ...
ReactionJoints_Array, ...
[0.025, 0.04, 0.05], ...
[true, true, true, true])
